[env]
MISE_USE_VERSIONS_HOST = "0"

[tasks.format]
description = "Format Lua scripts"
run = "pre-commit run --all-files"

[tasks.lint]
description = "Lint Lua scripts and GitHub Actions using hk"
run = "pre-commit run --show-diff-on-failure --all-files"

[tasks.ci]
description = "Run all CI checks"
depends = ["lint", "test"]
